force-app/main/default/objects/IntegrationLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/ExecutionDate__c.field-meta.xml
<CustomField>
    <fullName>ExecutionDate__c</fullName>
    <label>Execution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/ExternalIdList__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdList__c</fullName>
    <label>External Id List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/HasDeleted__c.field-meta.xml
<CustomField>
    <fullName>HasDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadIN__c.field-meta.xml
<CustomField>
    <fullName>PayloadIN__c</fullName>
    <label>Payload IN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadOUT__c.field-meta.xml
<CustomField>
    <fullName>PayloadOUT__c</fullName>
    <label>Payload OUT</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/domain/IntegrationLog/IntegrationLog.cls
public with sharing class IntegrationLog {
  public static String createLog(
    String integrationName,
    List<String> externalIdList,
    String recordTypeName,
    String payloadIN,
    String payloadOUT,
    String errorMessage,
    String endpoint,
    Integer statusCode,
    Boolean hasAnyErrors,
    Boolean hasDeleted,
    Order relatedOrder
  ) {
    System.debug('');
    Boolean attachmentIN = (payloadIN.length() > 130000);
    Boolean attachmentOUT = (payloadOUT.length() > 130000);
    Datetime datetimeNow = System.now();
    Id recordTypeId = Schema.SObjectType.IntegrationLog__c.getRecordTypeInfosByDeveloperName()
        .containsKey(recordTypeName)
      ? Schema.SObjectType.IntegrationLog__c.getRecordTypeInfosByName()
          .get(recordTypeName)
          .getRecordTypeId()
      : null;

    if (recordTypeId == null)
      System.debug(
        'Failed to get recordTypeId of integration log => ' + recordTypeId
      );

    IntegrationLog__c log = createIntegrationLogRecord(
      integrationName,
      externalIdList,
      recordTypeId,
      recordTypeName,
      attachmentIN,
      attachmentOUT,
      payloadIN,
      payloadOUT,
      errorMessage,
      endpoint,
      hasAnyErrors,
      datetimeNow,
      hasDeleted,
      relatedOrder
    );

    try {
      insert log;

      if (attachmentIN)
        createAttachment(
          log.Id,
          integrationName,
          'IN',
          log.Name,
          String.valueOf(datetimeNow),
          payloadIN
        );
      if (attachmentOUT)
        createAttachment(
          log.Id,
          integrationName,
          'OUT',
          log.Name,
          String.valueOf(datetimeNow),
          payloadOUT
        );
    } catch (Exception error) {
      System.debug(
        'EXCEPTION ON LOG - Please review parameters - ' +
          error.getMessage() +
          ' - ' +
          error.getStackTraceString()
      );
      log.Status__c = 'Error';
      log.ErrorMessage__c = error.getMessage();
    }

    return (String) log.Id;
  }

  public static IntegrationLog__c createIntegrationLogRecord(
    String integrationName,
    List<String> externalIdList,
    Id recordTypeId,
    String recordTypeName,
    Boolean attachmentIN,
    Boolean attachmentOUT,
    String payloadIN,
    String payloadOUT,
    String errorMessage,
    String endpoint,
    Boolean hasAnyErrors,
    Datetime datetimeNow,
    Boolean hasDeleted,
    Order relatedOrder
  ) {
    String externalIdString = String.join(externalIdList, ', ');
    return new IntegrationLog__c(
      Name = integrationName +
        ' ' +
        recordTypeName +
        ' - ' +
        (relatedOrder != null ? relatedOrder.ExternalId__c : 'N/A'),
      Endpoint__c = endpoint,
      ExternalIdList__c = externalIdString.length() > 255
        ? externalIdString.substring(0, 256)
        : externalIdString,
      RecordTypeId = recordTypeId,
      Attachment__c = (attachmentIN || attachmentOUT),
      PayloadIN__c = (attachmentIN ? '' : payloadIN),
      PayloadOUT__c = (attachmentOUT ? '' : payloadOUT),
      ExecutionDate__c = datetimeNow,
      Status__c = (hasAnyErrors ? 'Error' : 'Success'),
      ErrorMessage__c = errorMessage,
      HasDeleted__c = hasDeleted,
      Order__c = (relatedOrder != null ? relatedOrder.Id : null)
    );
  }

  @TestVisible
  private static Id createAttachment(
    String recordId,
    String integrationName,
    String inOrOut,
    String logName,
    String timeAsString,
    String payload
  ) {
    Attachment attachment = new Attachment(
      Name = 'LOG-' +
        integrationName +
        '-' +
        inOrOut +
        '-' +
        timeAsString +
        '.txt',
      Body = Blob.valueOf(payload),
      ParentId = recordId
    );

    insert attachment;

    return attachment.Id;
  }
}