force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Center__c/Distribution_Center__c.object-meta.xml
<CustomObject>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Type_of_shipping__c.field-meta.xml
<CustomField>
    <fullName>Type_of_shipping__c</fullName>
    <label>Type of shipping</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Production_Cost__c.field-meta.xml
<CustomField>
    <fullName>Production_Cost__c</fullName>
    <label>Production Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/Payment_Terms__c.object-meta.xml
<CustomObject>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/domain/DataIntegrationFields/DataIntegrationFields.cls
global with sharing class DataIntegrationFields {
    public interface FieldData {
        List<String> getRequiredFields();
        String getFieldKey();
        String getFieldId();
        String getExternalId();
        SObject deserialize();
    }
    
    public interface FieldDataChild {
        List<String> getRequiredFields();
        String getFieldId();
        String getFieldExternal();
        String getParentId();
        String getParentKey();
        SObject deserialize();
    }
    
    global class OrderINData implements FieldData { // extends OrderBase
        public String externalId;
        public String status;
        public String effectiveDate;
        public String accountExternalId;
        public String pricebook2ExternalId;
        public String shippingType;
        public String addressName;
        public String distributionCenterName;
        public String deliveryDate;
        public String paymentTermsName;
        public String contractExternalId;
        
        public List<OrderItemINData> orderItemList {get; set;}
        
        public Order deserialize() {
            return new Order(
                ExternalId__c	= this.externalId,
            Status			= this.status,
            EffectiveDate	= Date.valueOf(this.effectiveDate),
            Type_of_shipping__c 	= this.shippingType,
            Account		= new Account(ExternalId__c = this.accountExternalId),
            Pricebook2	= new Pricebook2(ExternalId__c = this.pricebook2ExternalId),
            Address__r = new Address__c(CEP__c = this.addressName),
            Distribution_Center__r = new Distribution_Center__c(Name = this.distributionCenterName),
            Delivery_Date__c = Date.valueOf(this.deliveryDate),
            Payment_Terms__r = new Payment_Terms__c(Name = this.paymentTermsName),
            Contract = new Contract(ExternalId__c = this.contractExternalId)
            );
        }
        
        public List<String> getRequiredFields() {
            return new List<String>{
                'ExternalId__c',
                'EffectiveDate',
                'Status'
            };
        }
        public List<String> getRequiredLookups() {
            return new List<String>{
                'AccountId',
                'Pricebook2Id'
            };
        }
        
        public String getFieldKey() {
            return 'ExternalId__c';
        }
        public String getFieldId() {
            return 'Id';
        }
        public String getExternalId() {
            return this.externalId;
        }
    }
    global class OrderItemINData implements FieldDataChild { // extends OrderItemBase
        public String id;
        public String externalId;
        public Decimal quantity;
        public String orderExternalId;
        public Decimal unitPrice;
        public Decimal sellingPrice;
        public Decimal productionCost;
        public String productExternalId;
        public String pricebookEntryExternalId;
        
        public OrderItem deserialize() {
            OrderItem orderItem = new OrderItem(
                ExternalId__c	= this.externalId,
                PricebookEntry		= new PricebookEntry(ExternalId__c = this.pricebookEntryExternalId),
                Quantity	= this.quantity,
                UnitPrice		= this.unitPrice,
                Selling_Price__c		= this.sellingPrice,
                Production_Cost__c		= this.productionCost
                );
            
            if (this.id == null || this.id == '') {
                orderItem.Order	= new Order(ExternalId__c = this.orderExternalId);
            }
            else orderItem.Id = this.id;
            
            return orderItem;
        }
        
        public List<String> getRequiredFields() {
            return new List<String>{
                'UnitPrice',
                'Quantity',
                'ExternalId__c'
            };
        }
        public List<String> getRequiredLookups() {
            return new List<String>{
                'OrderId',
                'Product2Id',
                'PricebookEntryId'
            };
        }
        
        public String getFieldId() {
            return 'Id';
        }
        public String getFieldExternal() {
            return 'ExternalId__c';
        }
        public String getParentId() {
            return 'OrderId';
        }
        public String getParentKey() {
            return this.orderExternalId;
        }
    }
    
    global virtual class Response {
        public String salesforceId;
        public String externalId;
        public String sobjectType;
        public Boolean hasError;
        public String errorMessage;
        
        public void success(String salesforceId, String externalId, String sobjectType){
            this.salesforceId	= salesforceId;
            this.externalId		= externalId;
            this.sobjectType	= sobjectType;
            this.hasError		= false;
        }
        
        public void error(String externalId, String errorMessage, String sobjectType){
            this.externalId		= externalId;
            this.sobjectType	= sobjectType;
            this.hasError		= true;
            this.errorMessage	= errorMessage;
        }
        
        public void error(String salesforceId, String externalId, String errorMessage, String sobjectType){
            this.salesforceId	= salesforceId;
            this.externalId		= externalId;
            this.sobjectType	= sobjectType;
            this.hasError		= true;
            this.errorMessage	= errorMessage;
        }
    }
    global class ResponseParent extends Response {
        public List<DataIntegrationFields.Response> items;
    }
}