force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Center__c/Distribution_Center__c.object-meta.xml
<CustomObject>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Tax_on_cost__c.field-meta.xml
<CustomField>
    <fullName>Tax_on_cost__c</fullName>
    <label>Tax on cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/service/TaxService/TaxService.cls
public class TaxService {
    public static void validateCategories(List<Tax__c> records){
        
        for(Tax__c tax : records){
            
            if(tax.Product__c == null){
                tax.addError('Product is required.');
            }
            
            if(tax.Distribution_Center__c == null){
                tax.addError('Distribution Center is required.');
            }
            
            if(tax.State__c == null){
                tax.addError('State is required.');
            }
        }
    }
    
    public static void validateDuplicates(List<Tax__c> newList){
        
        Set<String> keys = new Set<String>();
        
        for(Tax__c tax : [
            SELECT Product__c, Distribution_Center__c, State__c
            FROM Tax__c
        ]){
            keys.add(buildKey(tax));
        }
        
        for(Tax__c tax : newList){
            
            String key = buildKey(tax);
            
            if(keys.contains(key)){
                tax.addError('Duplicate tax configuration is not allowed.');
            }
            
            keys.add(key);
        }
    }
    
    private static String buildKey(Tax__c tax){
        return String.valueOf(tax.Product__c) + '-' +
            String.valueOf(tax.Distribution_Center__c) + '-' +
            String.valueOf(tax.State__c);
    }
    
    
    public static void applyTax(List<OrderItem> items){
        Set<Id> orderIds = new Set<Id>();
        
        for(OrderItem item : items){
            if(item.OrderId != null){
                orderIds.add(item.OrderId);
            }
        }
        
        Map<Id, Order> orders = new Map<Id, Order>([
            SELECT Id,
                   Distribution_Center__c,
                   Address__r.City__r.State__c
            FROM Order
            WHERE Id IN :orderIds
        ]);
        
        List<Tax__c> taxes = [
            SELECT Id,
                   Product__c,
                   Distribution_Center__c,
                   State__c,
                   Tax_on_cost__c
            FROM Tax__c
            WHERE Status__c = 'Approved'
        ];
        
        for(OrderItem item : items){
            
            Order order = orders.get(item.OrderId);
            
            if(order == null){
                item.addError('Order not found.');
                continue;
            }
            
            Id productId = item.Product2Id;
            Id dcId = order.Distribution_Center__c;
            if(order.Address__c == null || order.Address__r.City__r.State__c == null){
                item.addError('Order without complete address.');
                continue;
            }
            Id stateId = order.Address__r.City__r.State__c;
            
            
            Integer bestScore = -1;
            Tax__c bestTax;
            
            for(Tax__c tax : taxes){
                if(tax.Product__c == productId){
                    if(tax.Distribution_Center__c == dcId){
                        if(tax.State__c == stateId){
                                item.Tax_Percentage__c = tax.Tax_on_cost__c;
                        }
                    }
                }
                if(tax.State__c != stateId){
                    continue;
                }
            }
        }
    }
}